### ISSUE TITLE
FE: Basic/Beginning HTML Layout Part 2

### ISSUE THREAD

**Issue by Conecked** [Mekken/Project-1#13]
## User Story
User will navigate to the Website and should be able to navigate to elements on the page. The Basic Page should have a layout that is convenient for them to navigate.

## Acceptance Criteria
- [x] Create Grid System using Bootstrap (ex. Add container div w/ column div and row div) 
- [x] Add Search Input Bar (ex. Slack example Search Bars)
- [x] Add Div for Suggestions/Recommenedations (ex. Bootstrap Website Example in Slack)
- [x] Think of "Class" and "IDs" where necessary, ideas outline for future use

**Comment by Mekken** [comment]
Updated the User Story to better describe what we agreed on during our meeting 6/28/18

**Comment by Conecked** [comment]
I believe this is complete
